version: '3.8'

services:
  frontend:
    container_name: dazer_frontend
    image: ghcr.io/maiykol/dazer-frontend:development
    restart: always
    ports:
      - 8181:80
    networks:
      - dazer
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  backend:
    image: ghcr.io/maiykol/dazer-backend:development
    container_name: dazer_backend
    command: 
      - "sh"
      - "scripts/docker-entrypoint.sh"
    volumes:
      - dazer_dev_session_data:/usr/src/app/_sessions
    ports:
      - 8182:8000
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
  redis:
    image: redis
    container_name: dazer_redis
    networks:
      - dazer

  celery:
    restart: always
    container_name: dazer_celery
    image: ghcr.io/maiykol/dazer-backend:development
    command:
      - "sh"
      - "scripts/start-celery-worker.sh"
    volumes:
      - dazer_dev_session_data:/usr/src/app/_sessions
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer

  celery-beat:
    image: ghcr.io/maiykol/dazer-backend:development
    container_name: dazer_celery_beat
    command:
      - "sh"
      - "scripts/start-celery-beat.sh"
    volumes:
      - dazer_dev_session_data:/usr/src/app/_sessions
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer

  db:
    image: postgres:12.0
    container_name: dazer_db
    volumes:
      - dazer_dev_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    networks:
      - dazer

networks:
  dazer:

volumes:
  dazer_dev_postgres_data:
    external: true
  dazer_dev_session_data:
    external: true