version: '3.8'

services:

  web:
    build: ./
    container_name: dazer_web
    command: 
      - "sh"
      - "scripts/docker-entrypoint.sh"
    volumes:
      - sessions_data:/usr/src/app/_sessions
    ports:
      - 8000:8000
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer_net
    restart: always
      
  redis:
    image: redis
    container_name: dazer_redis
    restart: always
    networks:
      - dazer_net

  celery:
    restart: always
    container_name: dazer_celery
    build: ./
    command:
      - "sh"
      - "scripts/start-celery-worker.sh"
    volumes:
      - sessions_data:/usr/src/app/_sessions
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer_net

  celery-beat:
    build: ./
    container_name: dazer_celery_beat
    command:
      - "sh"
      - "scripts/start-celery-beat.sh"
    volumes:
      - sessions_data:/usr/src/app/_sessions
    env_file:
      - './.env'
    depends_on:
      - redis
    networks:
      - dazer_net
    restart: always

  db:
    image: postgres:12.0
    container_name: dazer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    networks:
      - dazer_net
    restart: always

networks:
  dazer_net:

volumes:
  postgres_data:
  sessions_data:
