# Generated by Django 4.2.6 on 2023-11-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('rows_removed', models.IntegerField(default=0)),
                ('columns', models.TextField()),
                ('categorical_columns_values', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('token', models.CharField(max_length=21, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('objective', models.CharField(choices=[('subsample', 'Subsample'), ('classification', 'Classification')], max_length=32)),
                ('parameters', models.TextField(default=None)),
                ('progress', models.FloatField(default=0.0)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('worker_id', models.CharField(max_length=128, null=True)),
                ('job_id', models.CharField(max_length=128, null=True)),
                ('done', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('status', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subsampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsample_id', models.CharField(max_length=10, unique=True)),
                ('keep_ratio_columns', models.TextField()),
                ('test_ratio', models.FloatField()),
                ('allowed_deviation', models.FloatField()),
                ('ratios', models.TextField()),
                ('iteration_random_states', models.TextField()),
                ('result_formatted', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='api.file')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='api.session')),
            ],
            options={
                'unique_together': {('session', 'file', 'subsample_id')},
            },
        ),
        migrations.AddField(
            model_name='file',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.session'),
        ),
        migrations.CreateModel(
            name='ClassificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_task_id', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=300)),
                ('evaluation', models.TextField()),
                ('feature_importances', models.TextField()),
                ('feature_columns', models.TextField()),
                ('target_column', models.CharField(max_length=100)),
                ('target_value', models.CharField(max_length=100)),
                ('cv', models.IntegerField()),
                ('random_states', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subsample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='api.subsampling')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('session', 'filename')},
        ),
    ]