# Generated by Django 4.2.6 on 2023-10-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=300)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "filename")},
            },
        ),
        migrations.CreateModel(
            name="Subsampling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsample_id", models.CharField(max_length=10, unique=True)),
                ("keep_ratio_columns", models.CharField(max_length=1100)),
                ("target_column", models.CharField(max_length=100)),
                (
                    "filename",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsamples",
                        to="api.file",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsamples",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "filename", "subsample_id")},
            },
        ),
    ]
