# Generated by Django 4.2.6 on 2023-11-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("rows_removed", models.IntegerField(default=0)),
                ("columns", models.TextField()),
                ("categorical_columns_values", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subsampling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsample_id", models.CharField(max_length=10, unique=True)),
                ("keep_ratio_columns", models.TextField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsamples",
                        to="api.file",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsamples",
                        to="api.session",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "file", "subsample_id")},
            },
        ),
        migrations.AddField(
            model_name="file",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="api.session",
            ),
        ),
        migrations.CreateModel(
            name="ClassificationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification_task_id",
                    models.CharField(max_length=10, unique=True),
                ),
                ("status", models.CharField(max_length=300)),
                ("evaluation", models.TextField()),
                ("feature_importances", models.TextField()),
                ("feature_columns", models.TextField()),
                ("target_column", models.CharField(max_length=100)),
                ("target_value", models.CharField(max_length=100)),
                (
                    "subsample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification",
                        to="api.subsampling",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("session", "filename")},
        ),
    ]
