# Generated by Django 4.2.6 on 2023-10-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsampling",
            old_name="filename",
            new_name="file",
        ),
        migrations.AlterUniqueTogether(
            name="subsampling",
            unique_together={("session", "file", "subsample_id")},
        ),
    ]
